package com.aigreentick.services.template.domain.enums;

public enum TemplateAuditEventType {

    TEMPLATE_CREATED,
    TEMPLATE_SUBMITTED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,
    TEMPLATE_BULK_DELETED,

    TEMPLATE_APPROVED,
    TEMPLATE_REJECTED,
    TEMPLATE_PAUSED,
    TEMPLATE_DISABLED,
    TEMPLATE_CATEGORY_CHANGED,

    TEMPLATE_SYNC_STARTED,
    TEMPLATE_SYNC_COMPLETED,
    TEMPLATE_SYNC_FAILED
}